### ISSUE TITLE
Missing math scope in hyperref

### ISSUE THREAD

**Issue by alexr00** [jlelong/vscode-latex-basics#75] opened 2023-12-05 09:57 UTC
Originally from @sleepymalc  in https://github.com/microsoft/vscode/issues/193248 

Steps to Reproduce:

1. Open a LaTeX file
2. Type `\hyperref[\( \)]{\( \)}`
3. Open `Developer: Inspect Editor Tokens and Scopes`
4. Move cursor within `\( \)`:
![image](https://github.com/microsoft/vscode/assets/60427058/068c0d62-9f3b-4627-ac05-2738222314da)

It's expected that it should contain at least one of `math` scopes such as follows:
![image](https://github.com/microsoft/vscode/assets/60427058/c0a14782-0bcc-4374-b46d-88b7df87ff0f)

**Comment by jlelong** [comment] 2023-12-05 20:27
Duplicate of #69. This was fixed upstream early November.

The LaTeX grammar in the main still points to a commit on September 16
https://github.com/microsoft/vscode/blob/48e93f756b764991ede33ad09781a863aca6907a/extensions/latex/syntaxes/LaTeX.tmLanguage.json#L7

I guess the fix will find its way to the next VS Code release.

**Closed by jlelong** 2023-12-05 20:27 UTC

**Comment by sleepymalc** [comment] 2023-12-05 20:30
I'm not familiar with how everything integrates, so should I expect a fix in the next VS Code update?

**Comment by jlelong** [comment] 2023-12-05 20:34
Yes, the fix will be integrated into the next VS Code update.
`vscode-latex-basics` only provides the LaTeX grammar and is also used by https://github.com/James-Yu/LaTeX-Workshop

If you use LaTeX-Workshop for typesetting LaTeX, you should already see the fix.

**Comment by alexr00** [comment] 2023-12-07 10:28
Great to hear that the issue is already fixed! I pull the LaTeX grammar into VS Coe about once per month, which means I'll be pulling in the changes next week and that they will be in the VS Code version that is released at the end of January.
